export enum ApiEnv {
  // Application
  ENV = 'ENV',
  PORT = 'PORT',
  CORS_ORIGIN = 'CORS_ORIGIN',

  // Database
  MONGODB_URI = 'MONGODB_URI',
  MONGODB_DBNAME = 'MONGODB_DBNAME',

  // Authentication & Security
  JWT_SECRET = 'JWT_SECRET',

  // OAuth - Facebook
  FACEBOOK_CLIENT_ID = 'FACEBOOK_CLIENT_ID',
  FACEBOOK_CLIENT_SECRET = 'FACEBOOK_CLIENT_SECRET',
  FACEBOOK_CALLBACK_URL = 'FACEBOOK_CALLBACK_URL',

  // OAuth - Google
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',

  // Google Ads
  GOOGLE_ADS_DEVELOPER_TOKEN = 'GOOGLE_ADS_DEVELOPER_TOKEN',

  // AWS Services
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_REGION = 'AWS_REGION',
  AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME',

  // Payment Processing
  STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
  STRIPE_WEBHOOK_SECRET = 'STRIPE_WEBHOOK_SECRET',

  // Email Service
  MAILGUN_API_KEY = 'MAILGUN_API_KEY',
  MAILGUN_DOMAIN = 'MAILGUN_DOMAIN',
}

export const APP_NAME = 'Clientfuse';
export const APP_DOMAIN = 'clientfuse.io';
