export enum ApiEnv {
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_REGION = 'AWS_REGION',
  AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  CORS_ORIGIN = 'CORS_ORIGIN',
  ENV = 'ENV',
  FACEBOOK_CALLBACK_URL = 'FACEBOOK_CALLBACK_URL',
  FACEBOOK_CLIENT_ID = 'FACEBOOK_CLIENT_ID',
  FACEBOOK_CLIENT_SECRET = 'FACEBOOK_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_ADS_DEVELOPER_TOKEN = 'GOOGLE_ADS_DEVELOPER_TOKEN',
  JWT_SECRET = 'JWT_SECRET',
  MONGODB_DBNAME = 'MONGODB_DBNAME',
  MONGODB_URI = 'MONGODB_URI',
  PORT = 'PORT',
}

export const APP_NAME = 'Clientfuse';
export const APP_DOMAIN = 'clientfuse.io';
