export enum ApiEnv {
  CORS_ORIGIN = 'CORS_ORIGIN',
  ENV = 'ENV',
  FACEBOOK_CALLBACK_URL = 'FACEBOOK_CALLBACK_URL',
  FACEBOOK_CLIENT_ID = 'FACEBOOK_CLIENT_ID',
  FACEBOOK_CLIENT_SECRET = 'FACEBOOK_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  JWT_SECRET = 'JWT_SECRET',
  MONGODB_DBNAME = 'MONGODB_DBNAME',
  MONGODB_URI = 'MONGODB_URI',
  PORT = 'PORT',
}
