export enum ServerErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INCORRECT_USER_OR_PASSWORD = 'INCORRECT_USER_OR_PASSWORD',
  AGENCY_NOT_FOUND = 'AGENCY_NOT_FOUND',
  INVALID_REQUEST = "INVALID_REQUEST",
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  API_ERROR = 'API_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR'
}
