export enum ServerErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INCORRECT_USER_OR_PASSWORD = 'INCORRECT_USER_OR_PASSWORD',
  AGENCY_NOT_FOUND = 'AGENCY_NOT_FOUND',
  CONNECTION_LINK_NOT_FOUND = 'CONNECTION_LINK_NOT_FOUND',
  INVALID_REQUEST = 'INVALID_REQUEST',
  FAILED_TO_SEND_EMAIL = 'FAILED_TO_SEND_EMAIL',
}
